const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'../..');
const memory={};
const window={localStorage:{getItem:k=>memory[k]||null,setItem:(k,v)=>{memory[k]=v;},removeItem:k=>delete memory[k]}};
window.STORY_EMBED={chapters:Object.fromEntries([1,2,3,4,5,6].map(n=>[n,JSON.parse(fs.readFileSync(path.join(root,'story/chapters/chapter'+n+'.json'),'utf8'))]))};
const ctx=vm.createContext({window,console});
for(const file of ['src/app/story-followthrough.js','story/story_manager.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);
const follow=window.StoryFollowthrough;
async function main(){
  assert.equal(follow.journal().length,0,'no spoiler entries at start');
  follow.completed(1,{id:'seq_002a'});
  assert.equal(follow.journal().length,1);
  assert.equal(follow.journal()[0].resolved,false);
  assert.ok(!follow.journal()[0].text.includes('枕元'),'question does not reveal answer');
  follow.completed(6,{id:'seq_ed1_wake4'});
  assert.equal(follow.journal()[0].resolved,true);
  assert.equal(follow.journal().length,1,'resolution cannot reveal unseen clues');
  assert.equal(follow.endingReview('ED4_SYNC'),null);
  const sm=new window.StoryManager();
  await sm.loadChapter(2);
  const event=sm.sequenceMap.get('seq_205_spawn_cards');
  sm.currentSequenceId=event.id;
  assert.equal(follow.canRecall(event.groupId,event.positions.map(p=>p.id)),false);
  sm.collect(event.groupId,'invented');
  assert.equal(sm.state.collected[event.groupId],undefined,'unknown items cannot create mastery');
  await sm.collect(event.groupId,'yarimizu');
  assert.equal(sm.state.routeFlags.firstFoundWater,true);
  for(const p of event.positions.filter(p=>p.id!=='yarimizu'))await sm.collect(event.groupId,p.id);
  assert.equal(follow.canRecall(event.groupId,event.positions.map(p=>p.id)),true);
  assert.equal(sm.currentSequenceId,'seq_206b');
  await sm.goNext('seq_follow_found_branch');
  assert.equal(sm.currentSequenceId,'seq_follow_water','exploration affects later dialogue');
  await sm.goNext(event.id);
  assert.equal(sm.currentSequenceId,'seq_206b','completed save does not spawn an empty collection');
  assert.equal(follow.canRecall(event.groupId,['future-card']),false,'new content must be played');
  await sm.loadChapter(3);
  await sm.goNext('seq_follow_bond');
  const before=JSON.stringify(sm.state.params);
  await sm.choose(1);
  assert.equal(sm.state.routeFlags.bondFriendship,true);
  assert.equal(JSON.stringify(sm.state.params),before,'relationship does not alter core ED scores');
  await sm.loadChapter(5);
  await sm.goNext('seq_follow_bond_return');
  assert.equal(sm.currentSequenceId,'seq_follow_friend_close','friendship is remembered');
  await sm.loadChapter(3);
  await sm.goNext('seq_304_trigger_kaimami');
  await sm.resumeFromMiniGame({success:false});
  assert.equal(sm.currentSequenceId,'seq_304_fail');
  await sm.goNext(sm.sequenceMap.get(sm.currentSequenceId).next);
  await sm.choose(0);
  assert.equal(sm.state.routeFlags.repairedKaimami,true,'failure leads to a playable repair');
  assert.equal(sm.currentSequenceId,'seq_follow_apology_wait');
  const old=new window.StoryManager();
  old.deserialize(JSON.stringify({version:1,state:{chapterId:1,params:{realityEgo:12}},currentSequenceId:'seq_003'}));
  assert.equal(old.state.params.realityEgo,12);
  assert.equal(old.state.history.length,0);
  follow.recordEnding('ED1_TRUE',sm.state);
  assert.ok(follow.endingReview('ED1_TRUE').choices.length>0,'ending has real choice history');
  const good=follow.renaiClosures({targetName:'葵の君',affection:65,stats:{modesty:10}});
  assert.equal(good.length,3,'successful romance permits non-romantic choices');
  const low=follow.renaiClosures({targetName:'雪の君',affection:0,stats:{modesty:3}});
  assert.equal(low.length,1);
  assert.equal(low[0].id,'farewell');
  assert.ok(low[0].reply.includes('返事は、届かなかった'),'no invented consent');
  memory['shinden3d-story-followthrough-v1']='{"read":"broken","mastered":[],"endings":null}';
  assert.doesNotThrow(()=>follow.completed(1,{id:'seq_002a'}));
  console.log('PASS: spoiler gating, collection mastery, discovery reaction, repair route, friendship callback, v1 migration, ending record, romance closures, damaged optional storage');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
