const { chromium } = require('playwright');
const { pathToFileURL } = require('url');
const path = require('path');
const fs = require('fs');
const assert = require('node:assert/strict');
(async () => {
  const out = path.resolve('artifacts/review'); fs.mkdirSync(out, {recursive:true});
  const browser = await chromium.launch({headless:true, channel:'chrome'});
  const page = await browser.newPage({viewport:{width:1440,height:900}});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.SHINDEN_ONLINE_CONFIG={enabled:false};});
  await page.goto(pathToFileURL(path.resolve('寝殿造り3D探訪_統合版.html')).href);
  await page.waitForFunction(()=>typeof APP!=='undefined');
  if(await page.locator('#onboardPanel.show').count())await page.locator('#onboardSkip').click();
  await page.waitForFunction(()=>!document.getElementById('loadingScreen').classList.contains('show'));
  await page.waitForTimeout(600);
  await page.screenshot({path:path.join(out,'title.png')});
  await page.locator('#btnWalk').click();
  await page.waitForTimeout(1800);
  await page.screenshot({path:path.join(out,'walk.png')});
  console.log(JSON.stringify(await page.evaluate(()=>({draws:renderer.info.render.calls,triangles:renderer.info.render.triangles,mode:APP.mode})),null,2));
  await page.setViewportSize({width:390,height:844});
  await page.reload(); await page.waitForFunction(()=>typeof APP!=='undefined');
  await page.waitForFunction(()=>!document.getElementById('loadingScreen').classList.contains('show'));
  await page.waitForTimeout(600);
  await page.screenshot({path:path.join(out,'mobile-title.png')});
  await page.locator('#btnWalk').click(); await page.waitForTimeout(1500);
  await page.screenshot({path:path.join(out,'mobile-walk.png')});
  await page.evaluate(()=>{hideModeBrief(true);showInfo('shinden');});
  await page.waitForTimeout(400);
  await page.screenshot({path:path.join(out,'mobile-info.png')});
  await page.setViewportSize({width:844,height:390});
  await page.reload();
  await page.waitForFunction(()=>typeof APP!=='undefined'&&!document.getElementById('loadingScreen').classList.contains('show'));
  await page.waitForTimeout(600);
  await page.screenshot({path:path.join(out,'landscape-title.png')});
  const modesFit=await page.locator('#mainModes .t-cat-btn').evaluateAll(buttons=>buttons.every(button=>{
    const r=button.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;
  }));
  assert.ok(modesFit,'all five mode buttons must fit on the landscape title');
  console.log(JSON.stringify({errors,out})); await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
